# Generated by Django 6.0 on 2026-01-01 23:48

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(choices=[('desenvolvimento', 'Desenvolvimento Web/App'), ('consultoria', 'Consultoria Técnica'), ('integracao', 'Integração de Sistemas'), ('outros', 'Outros Assuntos')], max_length=50)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lido', models.BooleanField(default=False)),
            ],
        ),
    ]
