# Generated by Django 6.0 on 2026-01-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name_plural': 'Mensagens'},
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='lido',
            new_name='lida',
        ),
    ]
